# Generated by Django 5.1.5 on 2026-05-23 13:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0009_merge_20260406_1726'),
        ('caja', '0004_cuenta_monto_cobrado_ventacaja_cliente_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del gasto')),
                ('monto', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Monto en Gs.')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('SERVICIOS', 'Servicios'), ('SUELDOS', 'Sueldos'), ('LIMPIEZA', 'Limpieza'), ('MANTENIMIENTO', 'Mantenimiento'), ('IMPUESTOS', 'Impuestos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de comprobante')),
                ('salio_de_caja', models.BooleanField(default=False, verbose_name='¿Salió de la caja?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10)),
                ('motivo_anulacion', models.TextField(blank=True, null=True, verbose_name='Motivo de anulación')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='caja.caja', verbose_name='Caja')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='administrador.proveedor', verbose_name='Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
