# Generated by Django 5.1.5 on 2026-05-23 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_merge_20260406_1726'),
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egreso', to='administrador.compra', verbose_name='Compra relacionada'),
        ),
    ]
