# Generated by Django 5.1.5 on 2026-05-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_egreso_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(choices=[('SERVICIOS', 'Servicios'), ('SUELDOS', 'Sueldos'), ('LIMPIEZA', 'Limpieza'), ('MANTENIMIENTO', 'Mantenimiento'), ('IMPUESTOS', 'Impuestos'), ('COMPRAS', 'Compras'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría'),
        ),
    ]
