# Generated by Django 5.1.5 on 2026-02-02 19:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categ', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Numero de factura')),
                ('fecha', models.DateField(verbose_name='Fecha de Compra')),
                ('iva_10', models.BigIntegerField(default=0)),
                ('iva_5', models.BigIntegerField(default=0)),
                ('total_sin_iva', models.BigIntegerField(default=0)),
                ('total_iva', models.BigIntegerField(default=0)),
                ('monto_total', models.BigIntegerField(default=0)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del item')),
                ('tipo', models.CharField(choices=[('MATERIA_PRIMA', 'Materia_Prima'), ('ARTICULO', 'Articulo')], default='ARTICULO', max_length=20, verbose_name='Tipo de item')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('gr', 'Gramo'), ('lt', 'Litro'), ('ml', 'Mililitro')], default='unidad', max_length=50)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_text', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='administrador.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('precio_compra', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio en Gs.')),
                ('subtotal', models.BigIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administrador.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='administrador.item')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.barrio')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.persona'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del producto')),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto/', verbose_name='Imagen')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('personalizable', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.categoriaproducto', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.persona')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='administrador.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cant_minima', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cant_maxima', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_ultima_entrada', models.DateField(auto_now_add=True)),
                ('fecha_ultima_salida', models.DateField(blank=True, null=True)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='administrador.detallecompra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='administrador.item')),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.persona')),
                ('salario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.salario')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.tipoempleado')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad usada en gramos(ej: 150) ', max_digits=10, verbose_name='cantidad en gramos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.item', verbose_name='Ingrediente (Item)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='administrador.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ingrediente del producto',
                'unique_together': {('producto', 'item')},
            },
        ),
    ]
