# Generated by Django 5.1.5 on 2026-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_direccion_latitud_alter_direccion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
