# Generated by Django 5.1.5 on 2026-03-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_direccion_latitud_alter_direccion_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='direccion',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.barrio'),
        ),
    ]
