# Generated by Django 5.1.5 on 2026-04-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_barrio_habilitado_direccion_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='tipo',
            field=models.CharField(choices=[('ingrediente', 'Ingrediente'), ('articulo', 'Artículo')], default='ingrediente', max_length=15, verbose_name='Tipo'),
        ),
    ]
