# Generated by Django 5.1.5 on 2026-04-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='es_mostrador',
            field=models.BooleanField(default=False),
        ),
    ]
