# Generated by Django 5.1.5 on 2026-04-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_categoriaproducto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienteproducto',
            name='puede_eliminarse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredienteproducto',
            name='puede_ser_extra',
            field=models.BooleanField(default=False),
        ),
    ]
