# Generated by Django 5.1.5 on 2026-04-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_ingredienteproducto_puede_eliminarse_and_more'),
        ('pedidos', '0008_remove_adicional_cantidad_remove_adicional_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='adicionales',
            field=models.ManyToManyField(blank=True, to='pedidos.adicional', verbose_name='Adicionales disponibles'),
        ),
    ]
