# Generated by Django 5.1.5 on 2026-04-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_mesa_es_mostrador'),
        ('administrador', '0008_producto_adicionales'),
    ]

    operations = [
    ]
