# Generated by Django 5.1.5 on 2026-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_merge_20260406_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoempleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
