# Generated by Django 5.1.5 on 2026-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_tipoempleado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
