# Generated by Django 5.1.5 on 2026-05-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_ciudad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(max_length=50, verbose_name='Numero de factura'),
        ),
    ]
