# Generated by Django 5.1.5 on 2026-05-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_alter_compra_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
