# Generated by Django 5.1.5 on 2026-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_categoriaproducto_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cant_maxima',
        ),
        migrations.AlterField(
            model_name='item',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('gr', 'Gramo')], default='unidad', max_length=50),
        ),
    ]
