# Generated by Django 5.1.5 on 2026-07-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_remove_stock_cant_maxima_alter_item_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cant_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
