# Generated by Django 5.1.5 on 2026-01-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_merge_20250527_1454'),
        ('administrador', '0018_merge_20250603_1107'),
    ]

    operations = [
    ]
