# Generated by Django 5.1.5 on 2025-03-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrador.persona')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_contratacion', models.DateField()),
                ('t_empleado', models.CharField(max_length=100)),
            ],
            bases=('administrador.persona',),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrador.persona')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
            ],
            bases=('administrador.persona',),
        ),
    ]
