# Generated by Django 5.1.5 on 2025-05-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0015_alter_item_options_producto_personalizable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(default='Pediente', max_length=20)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.IntegerField()),
                ('nota', models.TextField(blank=True, max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAdicionalPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.adicional')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='pedidos.detallepedido')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteEliminadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_eliminados', to='pedidos.detallepedido')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ingredienteproducto')),
            ],
        ),
    ]
