# Generated by Django 5.1.5 on 2026-02-08 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_direccion_latitud_alter_direccion_longitud'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='administrador.direccion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EC', 'En camino'), ('EN', 'Entregado'), ('CA', 'Cancelado')], default='RE', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RE', 'Retiro en local'), ('DE', 'Delivery')], default='PE', max_length=2),
        ),
    ]
