# Generated by Django 5.1.5 on 2026-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_direccion_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EC', 'En camino'), ('EN', 'Entregado'), ('CA', 'Cancelado')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RE', 'Retiro en local'), ('DE', 'Delivery')], default='RE', max_length=2),
        ),
    ]
