# Generated by Django 5.1.5 on 2026-03-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_delivery',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
