# Generated by Django 5.1.5 on 2026-03-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_costo_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_cocina',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En preparacion'), ('LI', 'Listo')], default='PE', max_length=2, verbose_name='Estado de cocina'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EN', 'Entregado'), ('FA', 'Facturado'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Estado de entrega'),
        ),
    ]
