# Generated by Django 5.1.5 on 2026-04-02 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_barrio_habilitado_direccion_barrio'),
        ('pedidos', '0005_remove_pedido_estado_pedido_estado_cocina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Item que se descuenta del stock al pedir este adicional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.item', verbose_name='Item de stock'),
        ),
    ]
