# Generated by Django 5.1.5 on 2026-04-03 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_mesa'),
        ('caja', '0002_cuenta_ventacaja_cuenta'),
        ('pedidos', '0005_remove_pedido_estado_pedido_estado_cocina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='caja.cuenta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='administrador.mesa', verbose_name='Mesa'),
        ),
    ]
