# Generated by Django 5.1.5 on 2026-04-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_adicional_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gramos que se descuentan del stock al pedir este adicional', max_digits=10, null=True, verbose_name='Cantidad en gramos'),
        ),
    ]
