# Generated by Django 5.1.5 on 2026-04-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_ingredienteproducto_puede_eliminarse_and_more'),
        ('pedidos', '0007_adicional_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicional',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='item',
        ),
        migrations.RemoveField(
            model_name='adicional',
            name='nombre',
        ),
        migrations.AddField(
            model_name='adicional',
            name='ingrediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.ingredienteproducto', verbose_name='Ingrediente del producto'),
            preserve_default=False,
        ),
    ]
