# Generated by Django 5.1.5 on 2026-04-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_producto_adicionales'),
        ('pedidos', '0008_remove_adicional_cantidad_remove_adicional_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicional',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='adicional',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad en gramos'),
        ),
        migrations.AddField(
            model_name='adicional',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.item', verbose_name='Item de stock'),
        ),
        migrations.AddField(
            model_name='adicional',
            name='nombre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
