# Generated by Django 5.1.5 on 2026-04-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_cuenta_pedido_mesa'),
        ('pedidos', '0009_remove_adicional_ingrediente_adicional_cantidad_and_more'),
    ]

    operations = [
    ]
