# Generated by Django 5.1.5 on 2026-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_merge_20260406_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('local', 'Local'), ('online', 'Online')], default='local', max_length=10),
        ),
    ]
