# Generated by Django 5.1.5 on 2026-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('EN', 'Entregado'), ('FA', 'Facturado'), ('CA', 'Cancelado'), ('PP', 'Pendiente de pago')], default='PE', max_length=2, verbose_name='Estado de entrega'),
        ),
    ]
