# Generated by Django 5.1.5 on 2026-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedido_estado_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
