# Generated by Django 5.1.5 on 2026-03-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('pedidos', '0005_remove_pedido_estado_pedido_estado_cocina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_pedido', to='pedidos.pedido'),
        ),
    ]
