# Generated by Django 5.1.5 on 2026-04-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cuenta_monto_cobrado_ventacaja_cliente_nombre_and_more'),
        ('facturacion', '0002_factura_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='venta_caja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='caja.ventacaja'),
        ),
    ]
