# Generated by Django 5.1.5 on 2026-03-30 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0005_barrio_habilitado_direccion_barrio'),
        ('pedidos', '0005_remove_pedido_estado_pedido_estado_cocina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.BigIntegerField(default=0, help_text='Monto en guaraníes con el que se abre la caja')),
                ('monto_final_esperado', models.BigIntegerField(default=0, help_text='Calculado: monto_inicial + ventas - egresos')),
                ('monto_final_real', models.BigIntegerField(blank=True, help_text='El dinero que realmente había al cerrar', null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_apertura', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cierre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('egreso', 'Egreso')], default='egreso', max_length=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.BigIntegerField(help_text='Monto en guaraníes')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.BigIntegerField(help_text='Total en guaraníes')),
                ('monto_recibido', models.BigIntegerField(help_text='Efectivo recibido')),
                ('vuelto', models.BigIntegerField(default=0)),
                ('tipo_entrega', models.CharField(choices=[('RE', 'Retiro en local'), ('DE', 'Delivery')], default='RE', max_length=2)),
                ('anulado', models.BooleanField(default=False)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.cliente')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venta_caja', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Venta de Caja',
                'verbose_name_plural': 'Ventas de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
