# Generated by Django 5.1.5 on 2026-04-03 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_mesa'),
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, help_text='Nombre opcional del cliente en mesa', max_length=100, null=True)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cobrada', 'Cobrada'), ('anulada', 'Anulada')], default='abierta', max_length=10)),
                ('total_cobrado', models.BigIntegerField(default=0)),
                ('monto_recibido', models.BigIntegerField(default=0)),
                ('vuelto', models.BigIntegerField(default=0)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='caja.caja')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='administrador.mesa')),
                ('usuario_cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Mesa',
                'verbose_name_plural': 'Cuentas de Mesa',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='ventacaja',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='caja.cuenta'),
        ),
    ]
