# Generated by Django 5.1.5 on 2026-04-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cuenta_ventacaja_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='total_cobrado',
        ),
    ]
