# Generated by Django 5.1.5 on 2026-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_remove_cuenta_total_cobrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='monto_cobrado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventacaja',
            name='cliente_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
